import React, { Fragment } from "react";
import BlogItem from "./BlogItem";
import blogImg1 from "../../../../images/blogImg1.jpg";
import blogImg2 from "../../../../images/blogImg2.jpg";
import blogImg3 from "../../../../images/blogImg3.png";
import blogImg4 from "../../../../images/blogImg4.jpg";

const Blogs = () => {
  const blogs = [
    {
      id: 1,
      title: "How do I file taxes if I havent in a while?",
      teaser:
        "Firstly, its best to understand that if you have a lot of years unfiled...",
      body:
        "Firstly, its best to understand that if you have a lot of years unfiled, you should make sure that you do all of your filings at once.  If this requires getting a lot of documents together, it is best to create a personal folder or box to keep yourself organized. In order to file at minimum you need the year in questions W-2 if you were a wage earner that year or 1099 if you were a contractor or had an annuity payout of some sort. Many of these documents are generated by the IRS when you fail to file, but they do not go through any sort of deduction process. This can lead to a tremendous balance. Ensure that you KEEP RECEIPTS or any paper work  or to be prepared to contact people for documentation reguarding significant purchases or expenses.  Finally, its best to visit a tax attorney when you have many years unfiled, often there is going to be a balance and it may be significantly larger than what the taxpayer is expected to pay. Aggressive tax specialists like those at the National Tax Group save clients millions. The IRS offers programs for relief, but very little guidance in acheiving said resolution. These Tax Pros can turn your debt into pennies on the dollar by utilizing government programs and a deep deep knowledge of the tax code. On Average we save our clients 93 percent.  ",
      img: blogImg1,
      postDate: "5/20/2020",
    },
    {
      id: 2,
      title: "Should I Incorporate?",
      teaser: "You can save money on the self employment tax...",
      body:
        "You can save money on the self employment tax by encorporating yourself. Working for yourself is becoming far more common in 2020. The gig economy and service industry led to an entire generation of tax payers who are 1099. Not to mention the endless tradesmen who care more about their product the books. These people end up paying thousands in self employment tax and estimated quarterlies. Or worse, they don't pay enough, and get hit with a tax lien that is multiplied to the nth degree for 1099 recipients.  The worst hit are truck drivers. Thats because they are compensated againt fuel cost, but if that is not considered by the IRS, which they often do not if you underpay according to their estimates, your liability can quadruple very very quickly if you are late or worse do not pay at all. This is why we recommend working with a CPA to take your personal earnings given to you in 1099 and transforming that to an S-Corporation where in you become a w-2 employee.  This move alone without taking advantage of the aggressive nature of the corporate tax code,  saves clients thousands. Then if you are able to actually posture yourself as a more complex entity, and take advantage of the litany of available breaks to corporations your overall tax burden can decrease by thousands. Not to mention that when it comes time for you to file, its as simple as filing a w-2.  Of course, now that you are a corporation, there is a system of books and payroll that needs to be managed or else you can find yourself in hot water with the IRS and State. Hiring a CPA to handle this process can be a financially efficient strategy. When overtime you pay a nominal fee to someone who provides an absolutely rigid set of filings that the IRS accepts with out question. It effectively pays for itself if you are in an industry where you gross receipts are high but your overhead is as well by eliminating so many extra quarterly expenditures. To set up your corporation call National Tax Group today. ",
      img: blogImg3,
      postDate: "6/1/2020",
    },
    {
      id: 3,
      title: "What is a tax lien?",
      teaser: "Referring to the IRS website...",
      body: `Referring to the IRS website: "A federal tax lien is the government’s legal claim against your property when you neglect or fail to pay a tax debt. The lien protects the government’s interest in all your property, including real estate, personal property and financial assets. A federal tax lien exists after The IRS Puts your balance due on the books (assesses your liability);
              Sends you a bill that explains how much you owe (Notice and Demand for Payment) and You neglect or refuse to fully pay the debt in time. You can avoid a federal tax lien by simply filing and paying all your taxes in full and on time. If you can’t file or pay on time, don’t ignore the letters or correspondence you get from the IRS. If you can’t pay the full amount you owe, payment options are available to help you settle your tax debt over time."`,
      img: blogImg2,
      postDate: "3/13/2020",
    },
    {
      id: 4,
      title: "Taking Advantage of the Tax Code: Part 1",
      teaser: "Tax Exemptions for Middle Class Americans",
      body: `
      
      Here are some examples of ways you can save on your tax bill
      
     1) Deductible IRA Contributions: A 401(k) through work that you fund with pre-tax dollars automatically reduces your taxable income. You can get  tax break by contributing to a traditional IRA and taking an above-the-line tax deduction when you fill out your tax returns. Your taxable income decreased by the amount you contribute to your IRA. A wealthy individual in the same position would not be able to deduct his or her IRA contributions.

2) The Home-Sale Exclusion: If you sell your home you don’t owe the IRS long-term capital gains taxes on the first $250,000 of profit (or $500,000 for a married couple filing jointly). Since most middle-class folks won’t see more than $250,000 in profits from the sale of their primary residence anyway, the home-sale exclusion represents a nice tax break for the middle class. It’s one of the reasons that owning a home can make financial sense.

3) The Saver’s Tax Credit: Working class Americans who manage to put together some savings can claim the Saver’s Tax Credit when they fill out their returns. It’s a tax break designed to give people an incentive to save money. This is especially important because so many people lack an emergency fund and have zero or insufficient retirement savings. The Saver’s Tax Credit is not refundable. It can reduce your tax bill to zero, but if the amount of your credit is greater than what you owe the IRS you won’t get the difference refunded to you.

4) Earned Income Tax Credit: If you have a job but it’s not bringing in much income you can claim the Earned Income Tax Credit (EITC). Like any tax credit, the EITC directly reduces your tax bill by the size of the credit. Unlike the Saver’s Tax Credit, the EITC is refundable. If the amount of the EITC is greater than the amount you owe the IRS, you’ll get the difference refunded to you. The EITC has been very successful in reducing poverty among working-class families.`,
      img: blogImg4,
      postDate: "1/29/2020",
    },
  ];

  return (
    <Fragment>
      <h2 className='text-center lead'>
        <span className='text-primary'>Read</span>
        <br />
        The Latest
      </h2>
      <div style={blogStyle}>
        {blogs.map((blog) => (
          <BlogItem key={blog.id} blog={blog} />
        ))}
      </div>
    </Fragment>
  );
};

const blogStyle = {
  display: "grid",
  gridTemplateColumns: "repeat(4,1fr)",
  gridGap: "1rem",
};

export default Blogs;
